export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#ffb3d9',
        'primary-container': '#e91e8c',
        'on-primary': '#3d0020',
        'on-primary-container': '#ffd6e8',
        'primary-fixed': '#ffd6e8',
        'primary-fixed-dim': '#ffb3d9',
        'on-primary-fixed': '#2d0016',
        'on-primary-fixed-variant': '#8c0048',
        secondary: '#ffccd5',
        'secondary-container': '#c2185b',
        'on-secondary': '#3d0018',
        'on-secondary-container': '#ffd6e8',
        'secondary-fixed': '#ffd6e8',
        'secondary-fixed-dim': '#ffccd5',
        'on-secondary-fixed': '#1f000a',
        'on-secondary-fixed-variant': '#7a0034',
        tertiary: '#ffb786',
        'tertiary-container': '#df7412',
        'on-tertiary': '#502400',
        'on-tertiary-container': '#461f00',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-fixed-dim': '#ffb786',
        'on-tertiary-fixed': '#311400',
        'on-tertiary-fixed-variant': '#723600',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        surface: '#0b1326',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-variant': '#2d3449',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#c2c6d6',
        'outline': '#8c909f',
        'outline-variant': '#424754',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        'inverse-primary': '#d81b60',
        background: '#0b1326',
        'on-background': '#dae2fd',
        'surface-tint': '#ffb3d9',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'container-padding': '40px',
        'card-gap': '24px',
        unit: '8px',
        gutter: '24px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['96px', { lineHeight: '110px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'title-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}